; SPDX-FileCopyrightText: 2026 José Bollo
;
; SPDX-License-Identifier: MIT
; SRFI-266 demo by José Bollo, 2026

(include "expr.scm")


(use-modules (language tree-il))


(for-each
  (lambda (x)
    (display (cons 'expr x))
    (display " => ")
    (display (tree-il->scheme (macroexpand (cons 'expr x))))
;    (display " => ")
;    (display (macroexpand (cons 'expr x)))
    (newline))
  '(
    (1)
    (a)
    ((a))
    (((f0)))
    (- a)
    (- a + b)
    (+ a)
    (+ - a)
    (? a)
    (a + b)
    (a + b + c)
    (a - b)
    (a - b - c)
    (a + b - c - d - e + 4 + 5 * f)
    (a / b)
    (a / b / c)
    (a * b)
    (a * b * c)
    (a + b * c * d)
    (a * b + c * d)
    (a \ b)
    (a \ b \ c)
    (a % b)
    (a % b % c)
    (1 << a % 8)
    (f1 a)
    (f1 a + b)
    (f1 a * b)
    (f1 (a + b))
    (f3 (a b + c d))
    (f2 ((a + b) c))
    (f1 g1 a)
    ((ff g1) a)
    (ff1 (g a))
    (cos 2 * a + sin 3 * b)
    (square cos a + square sin b)
    (a < b < c)
    (a < b <= c)
    (a < b <= c < d)
    (a = b = c < d < e)
    (@ B != 78)
    (u implies z)
    (a and b and c or u or v and not i)
    ((a and b and c) or u or (v and not i))
    (a and b and (c or u or v) and not i)
    (45 if a else 28)
    (a + b if x implies y else 7 * b + a)
    (a if (b if c else d) else e)
    (a if b if c else d else e)
    (a + b as c in c * d)
    (a + b as v in 4 * v ** 2 + 5 * v + 34)
    (a + b as v in 4 * v ** 2 + 5 * v - 34)
    (a + b as v in 4 * v ** 2 - 5 * v + 34)
    (floor/ (a b) as q r in q + ? positive? r)
    (a if (b if (u as v in w) else d) else e)
    (a if b if u as v in w else d else e)
   ))

